name: CI 
# Controls when the workflow will run
on: 
 # Triggers the workflow on push or pull request events but only for master branch
 push: 
   branches: [publish]

 
 #Allow you to run this workflow manually from the actions tab workflow_dispatch;

 workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build: 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that eill be executed as part of the jobs
    steps:
      - uses: actions/checkout@v2 
      
        name: Loginn to DOcker Hub
      - uses: docker/login-action@v1
        with:
          username: fordevio
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1 

      - 
        name: Build and push 
        uses: docker/build-push-action@v2 
        with:
          context: .
          file: ./deployment/Dockerfile
          push: true 
          tags: fordevio/wharf:latest

